### ISSUE TITLE
trusted connections do not work

### ISSUE THREAD

**Issue by Jeff-Winchell** [Microsoft/SQL-Server-R-Services-Samples#1]
When you use trusted_connection=true in the connection string, RxInSqlServerData and RxSqlServerData return the error message:
Error in .rxEnsureOdbcCredentials(connectionString, server, databaseName,  : 
  The Trusted_Connection keyword is not allowed in connection string.

Please document a reliable way to use integrated security since it was announced as working since RC2 and put it clearly in your What's New documents since finding the connection string is virtually an exercise in google futility.

**Comment by hlums** [comment]
Hi Jeff,

Can you specify in which script you got the error? I just did some testing on the R code of the energy forecast template and it worked fine for both RC2 and RC3. 

Thank you!
Hong

**Comment by Jeff-Winchell** [comment]
I don't know why I saw what I did before, but I don't now.

But I would still add a line in the docs that cleary says how both types of connection strings are formed.

**Comment by hlums** [comment]
Will do. Thanks for the feedback!

**Comment by Jeff-Winchell** [comment]
Thank you for your product!
- sent from my sometimes smart phone
