### ISSUE TITLE
R Script error in Step 5 of SQL R

### ISSUE THREAD

**Issue by Harsh-Singh-1** [Microsoft/SQL-Server-R-Services-Samples#14]
Getting the following error in Step 5 of the \SQLR-Fraud-Detection.ps1 walkthrough script. 

Invoke-Sqlcmd : A 'R' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
An external script error occurred: 
The response variable 'Label' has only one level.
It must have at least 2 levels to fit a classification tree.
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  The response variable 'Label' has only one level.
It must have at least 2 levels to fit a classification tree.
Calls: source ... tryCatch -> tryCatchList -> tryCatchOne -> doTryCatch -> .Call
Error in ScaleR.  Check the output for more information.
Error in eval(expr, envir, enclos) : 
  Error in ScaleR.  Check the output for more information.
Calls: source -> withVisible -> eval -> eval -> .Call
Execution halted
At    \SQLR-Fraud-Detection.ps1:63 char:5
-     Invoke-Sqlcmd -ServerInstance $ServerName  -Database $DBName -Que ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
  - FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

**Comment by jeroenterheerdt** [comment]
This solution has moved to [Microsoft/r-server-fraud-detection](https://github.com/Microsoft/r-server-fraud-detection). If you are still having issues (this is an old issue) please report it there.
