### ISSUE TITLE
text files do not get uploaded in to sql server tables in energy demand forecasting ??

### ISSUE THREAD

**Issue by kamalpradhan95** [Microsoft/SQL-Server-R-Services-Samples#2]
the script executes successfully but no changes are reflected in database.

**Comment by kamalpradhan95** [comment]
i think there is some error in bcp file upload.

**Comment by hlums** [comment]
A few possible fixes
1) For the SQL server name, can you add the port number? For example, APTUS_HP, 1433. 1433 is the default port number for SQL server. If you specified a different one for your server, use that.
2)How did you get the repo? Did you do a git clone or download zip file? We recently noticed that downloading the zip file and unzipping it broke the format of the input data, i.e. the line endings are gone. We are still looking for a fix for this. If you downloaded zip file, can you try git clone? 
3)There should be a "logs" directory created under "SQLR". Please check the "setup" text file. We are aware that the header in the data caused an "Invalid character value for cast specification" error. A fix for this will come out in the next couple of days. However, this shouldn't affect the uploading of the rest of the data. If the data uploading is successful, the log file should say "140160 rows copied." and "35040 rows copied." for the two data files.
Please remove your screenshot as it has sensitive information.

**Comment by kamalpradhan95** [comment]
thank you hong. this is my setup file. please have a look.

## Deploy Start Date = 2016-05-17 23:37:09

Starting copy...
SQLState = 22003, NativeError = 0
Error = [Microsoft][ODBC Driver 13 for SQL Server]Numeric value out of range

0 rows copied.
Network packet size (bytes): 4096
Clock Time (ms.) Total     : 16    

Starting copy...
SQLState = 22005, NativeError = 0
Error = [Microsoft][ODBC Driver 13 for SQL Server]Invalid character value for cast specification

0 rows copied.
Network packet size (bytes): 4096
Clock Time (ms.) Total     : 1

**Comment by hlums** [comment]
Can you confirm how you get the repository? It looks like your error is caused by downloading the zip file. You can open one of the data files under "Data" directory in Notepad and check if all the data are shown in one line. If so, please try using git clone to get a local copy of the repository.

**Comment by kamalpradhan95** [comment]
ok i have cloned the repository and it works fine. but the graphs are not getting updated. the demand forecast table is also empty.
![capture](https://cloud.githubusercontent.com/assets/19342973/15332002/c8bb45e2-1c18-11e6-9589-d2023faf5705.PNG)

here is the create job log file.

Changed database context to 'forecst'.
forecst
APTUS_HP
NA
SQLServerAgent is not currently running so it cannot be notified of this action.
SQLServerAgent is not currently running so it cannot be notified of this action.
exec [dbo].[usp_energyDemandForecastMain] '101', 'APTUS_HP', 'forecst', 'sa', '*****','NO'
SQLServerAgent is not currently running so it cannot be notified of this action.
exec [dbo].[usp_energyDemandForecastMain] '102', 'APTUS_HP', 'forecst', 'sa', '*****','NO'
SQLServerAgent is not currently running so it cannot be notified of this action.
exec [dbo].[usp_energyDemandForecastMain] '103', 'APTUS_HP', 'forecst', 'sa', '*****','NO'
SQLServerAgent is not currently running so it cannot be notified of this action.
exec [dbo].[usp_energyDemandForecastMain] '104', 'APTUS_HP', 'forecst', 'sa', '*****','NO'
SQLServerAgent is not currently running so it cannot be notified of this action.

**Comment by hlums** [comment]
You need to start SQL Server Agent on your server. If you have SQL Server Management Studio, you can see it in the Object Explorer on the left side. Right click on it and click start. 
If you don't have SQL Server Management Studio. Search for "Services" on your server and run it, you will see SQL Server Agent in the list of services. Right click on it and start.

**Comment by kamalpradhan95** [comment]
the sql server agent is running but the jobs are not executed.

![capture2](https://cloud.githubusercontent.com/assets/19342973/15333877/4cadac62-1c20-11e6-8e78-2f591473a457.PNG)

create job log

Changed database context to 'testdb'.
testdb
APTUS_HP
NA
exec [dbo].[usp_energyDemandForecastMain] '101', 'APTUS_HP', 'testdb', 'sa', 'aptus123','NO'
exec [dbo].[usp_energyDemandForecastMain] '102', 'APTUS_HP', 'testdb', 'sa', 'aptus123','NO'
exec [dbo].[usp_energyDemandForecastMain] '103', 'APTUS_HP', 'testdb', 'sa', 'aptus123','NO'
exec [dbo].[usp_energyDemandForecastMain] '104', 'APTUS_HP', 'testdb', 'sa', 'aptus123','NO'

db creation log

Changed database context to 'msdb'.
Configuration option 'show advanced options' changed from 0 to 1. Run the RECONFIGURE statement to install.
Configuration option 'Agent XPs' changed from 1 to 1. Run the RECONFIGURE statement to install.
Configuration option 'show advanced options' changed from 1 to 0. Run the RECONFIGURE statement to install.
Changed database context to 'testdb'.

(1 rows affected)

(1 rows affected)

(1 rows affected)

(1 rows affected)

(1 rows affected)

(1 rows affected)

(1 rows affected)
T h e   m o d u l e   ' u s p _ e n e r g y D e m a n d F o r e c a s t M a i n '   d e p e n d s   o n   t h e   m i s s i n g   o b j e c t   ' u s p _ f e a t u r e E n g i n e e r i n g ' .   T h e   m o d u l e   w i l l   s t i l l   b e   c r e a t e d ;   h o w e v e r ,   i t   c a n n o t   r u n   s u c c e s s f u l l y   u n t i l   t h e   o b j e c t   e x i s t s . 

 **T h e   m o d u l e   ' u s p _ e n e r g y D e m a n d F o r e c a s t M a i n '   d e p e n d s   o n   t h e   m i s s i n g   o b j e c t   ' u s p _ p e r s i s t M o d e l ' .   T h e   m o d u l e   w i l l   s t i l l   b e   c r e a t e d ;   h o w e v e r ,   i t   c a n n o t   r u n   s u c c e s s f u l l y   u n t i l   t h e   o b j e c t   e x i s t s .** 

couldn't understand the above error written in bold letters.

**Comment by hlums** [comment]
That's just a warning, because some stored procedures needed by this stored procedure are created after it. It doesn't matter. 
Did the jobs get cancelled by themselves? I have never seen this before. Maybe you need to verify your SQL Server Agent is working properly by scheduling some simple jobs. Also, make sure that your SQL Server R Services is properly configured. 
BTW, don't run to many jobs concurrently if your server is not very Powerful. It may cause out of memory error later.

**Comment by kamalpradhan95** [comment]
only the yellow line changes other tiles are just blank.

![capture 3](https://cloud.githubusercontent.com/assets/19342973/15335100/b943a7d2-1c25-11e6-9940-51e46889e436.PNG)

**Comment by hlums** [comment]
Can you post the current screenshot of your Job Activity Monitor? Also, execute "SELECT \* FROM runlogs" to see if there is any -1 in the "success_flag" field. If yes, what are the error messages?

**Comment by kamalpradhan95** [comment]
is works fine now just had to disable the windows firewall outbound rules for "Block network access for R local user accounts in SQL Server Instance MSSQLSERVER". thanks for the help.

can you please tell how to decrease the refresh time and how to enable auto refresh ??

**Comment by hlums** [comment]
By "decrease the refresh time", do you mean decrease the frequency of the SQL jobs? You'll need to modify the frequency of each job in src\sql\usp_create_and_delete_jobs. See https://msdn.microsoft.com/en-us/library/ms187320.aspx for more details on how to change the schedule.
See https://powerbi.microsoft.com/en-us/documentation/powerbi-refresh-scheduled-refresh/#whats-supported for how to enable auto refresh in Power BI. With the free version, you can only do daily auto refresh.

**Comment by kamalpradhan95** [comment]
thank for the help !! it's a great tutorial.
