### ISSUE TITLE
Fraud Detection Error Message

### ISSUE THREAD

**Issue by ZhouFang928** [Microsoft/SQL-Server-R-Services-Samples#20]
Hi zhixingr,

I tried out the Fraud Detection example but got the following error message when executing rxExec function in the script 01-generate-tagged-data.R.

> #rxExec function allows distributed execution of a function in parallel across nodes (computers) or cores of a "compute context" such as a cluster
+ rxExec(tag_fraud, 
+        in_table1 = untagged_table,
+        in_table2 = fraud_table,
+        out_table = tagged_fraud_table,
+        tag_mode = "Acct")
======  DATASCISQL16DB  ( process  1 ) has started run at  2017-01-05 02:42:45.93  ====== 
 
DATASCISQL16DB [6024]: Rows Processed: 50000 
DATASCISQL16DB [6024]: Rows Processed: 100000 
DATASCISQL16DB [6024]: Rows Processed: 150000 
DATASCISQL16DB [6024]: Rows Processed: 200000 
 
DATASCISQL16DB [6024]: Rows Processed: 8640 
 
DATASCISQL16DB [6024]: Rows Processed: 10000 
Failed to allocate 20480000 bytes. 
Caught exception in file: CxAnalysis.cpp, line: 6488. ThreadID: 3036 Rethrowing. 
Caught exception in file: CxAnalysis.cpp, line: 5682. ThreadID: 3036 Rethrowing. 
Caught exception in file: CxAnalysis.cpp, line: 5249. ThreadID: 3036 Rethrowing. 
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  bad allocation 
Calls: source ... tryCatch -> tryCatchList -> tryCatchOne -> doTryCatch -> .Call 
In addition: Warning messages: 
1: In as.POSIXlt.POSIXct(x, tz) : unable to identify current timezone 'C': 
please set environment variable 'TZ' 
2: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'localtime' 
Execution halted 
Error in rxCompleteClusterJob(hpcServerJob, consoleOutput, autoCleanup) : 
  No results available - final job state: failed

Could you please kindly advise? Thanks a lot!

**Comment by DataIntelytics** [comment]
Hello -- It looks like you need to specify a time zone.
