### ISSUE TITLE
Tangentially related issue

### ISSUE THREAD

**Issue by wbuchanan** [Microsoft/SQL-Server-R-Services-Samples#21]
I've tried getting RServices installed and set up on my organization's SQL Server 2016 Standard instance several times now.  Each time I follow the set up/installation instructions published on [Microsoft's website](https://msdn.microsoft.com/en-us/library/mt696069.aspx) and it has yet to succeed.  

I have the Launchpad service started and all of the MSSQLSERVER users are created as is the SQLRUserGroup logon.  I've granted permissions to execute external scripts and am one of the sys admins on the server itself.  However, no matter what I do I always get the same uninformative error message:

```SQL
exec sp_configure 'external scripts enabled', 1
reconfigure with override;

Exec sp_configure  'external scripts enabled';

exec sp_execute_external_script  @language =N'R',  
@script=N'OutputDataSet<-InputDataSet',    
@input_data_1 =N'select 1 as hello'  
with result sets (([hello] int not null));  
go  

Msg 39011, Level 16, State 1, Line 1
SQL Server was unable to communicate with the LaunchPad service. Please verify the configuration of the service.  
Msg 11536, Level 16, State 1, Line 1
EXECUTE statement failed because its WITH RESULT SETS clause specified 1 result set(s), but the statement only sent 0 result set(s) at run time.
```

Is it asking too much to get installation instructions that will work as expected or for more complete installation/troubleshooting documentation to be published?  For example, some users have mentioned something about a `db_rrerole` database role, but this isn't created when I work through the installation process and since there isn't any mention of this role in the official documentation I have no way of knowing if this was something only needed during the community testing release or if it is still required in the current release.

**Comment by jeroenterheerdt** [comment]
Although this is an old issue, please note that this repo is for samples only. If you have issues with RServices, please use [our forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ropen).
