### ISSUE TITLE
Error Normalizing train_features

### ISSUE THREAD

**Issue by kibtes** [Microsoft/SQL-Server-R-Services-Samples#22]
This Error is displayed when running code on line 298 of 01-data-preparation.R

ERROR: The sample data set for the analysis has no variables.
Caught exception in file: CxAnalysis.cpp, line: 3756. ThreadID: 12080 Rethrowing.
Caught exception in file: CxAnalysis.cpp, line: 5249. ThreadID: 12080 Rethrowing.
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  ERROR: The sample data set for the analysis has no variables.

I suppose this error occurs due to the NULL value on the sd features for id=1 . An i really don't know how to remove this NULL values. I kindly need your help/assistance in removing this NULL values if that is the problem leading to this Error. Else what could be the reason for it to lead to an Error while everything works out for the normalization of test_features? And also in the test_features after being Normalized the columns setting3, s1, a1 and sd1 are missing.

**Comment by jeroenterheerdt** [comment]
Although this is an old issue, please note that this repo is for samples only. If you have issues with RServices, please use [our forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ropen).
