### ISSUE TITLE
Cannot communicate with the MS Launchpad Service

### ISSUE THREAD

**Issue by wbuchanan** [Microsoft/SQL-Server-R-Services-Samples#23]
Followed the installation instructions for RServices in SQL Server 2016, but am not able to test any of these due to this issue.  I've tried searching for solutions every where and have lost a few days of time trying to find the solution with no luck to date.

**Comment by jeroenterheerdt** [comment]
Although this is an old issue, please note that this repo is for samples only. If you have issues with RServices, please use [our forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ropen).
