### ISSUE TITLE
Error in Galaxies

### ISSUE THREAD

**Issue by AbouzarITMan** [Microsoft/SQL-Server-R-Services-Samples#24]
Hello,
I tried Galaxies sample,but i got error "C:/Galaxies/data/galaxiesTraining.csv" 
after invoke stored procedure 'TrainGalaxiesNN'.
I think ,It need file galaxiesTraining.csv for tranining.
thanks

**Comment by IvanMokrov** [comment]
Check a path, maybe your files isn't on "C:/Galaxies" folder?
You may change the paths in galaxiesTraining.csv also (via any texteditor) to change the path's to DATA with images
