### ISSUE TITLE
can we ask Qs about it? 

### ISSUE THREAD

**Issue by NebileK** [Microsoft/SQL-Server-R-Services-Samples#28]
while implementing the project on my computer, there is an error in sql. the error says "Msg 208, Level 16, State 1, Procedure PredictChurnR, Line 9 [Batch Start Line 39]
Invalid object name 'ChurnModelR'." How can I cope with it?

**Comment by NebileK** [comment]
Hi, many thanks to your interest in my question. I solve the problem by restart some services and reset user rights on SQL server. It works now and I am so happy. It is my first experience on this topic. It is important for me. Now, I can not understand the file with the extension .ps1..... Without it can I modify your project to my case?I have read the readme file well. I searched on the internet, but still it is not very clear.  Best Regards-Nebile

**Comment by jeroenterheerdt** [comment]
`.ps1` is a Powershell script that allows for automation of certain tasks.
