### ISSUE TITLE
Additional information on predictive maintenance modeling guide

### ISSUE THREAD

**Issue by maechler** [Microsoft/SQL-Server-R-Services-Samples#30]
Is there any additional information about this simulated dataset (https://github.com/Microsoft/SQL-Server-R-Services-Samples/tree/master/PredictiveMaintanenceModelingGuide/Data)?

1. What real machine is simulated here?
2. What are the units of measurement for these sensors?
3. What do the different machine models stand for?
4. What do the different machine components stand for?
5. What do the different errors stand for?

**Comment by Juvago** [comment]
I am interested on the same questions.
Does someone know where the data is coming from and for which application it was used?
Thank you in advance!

**Comment by jeroenterheerdt** [comment]
unfortunately we cannot provide the extra information at this time.
