### ISSUE TITLE
step 3a fails - contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by imtiazu** [Microsoft/SQL-Server-R-Services-Samples#34]
Hi I have tried to walk through the PS steps but keeps erroring on 3a... any ideas? Thanks.

Invoke-Sqlcmd : A 'R' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
An external script error occurred:
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Calls: source ... model.matrix -> model.matrix.default -> contrasts<-
Error in ScaleR.  Check the output for more information.
Error in eval(expr, envir, enclos) :
  Error in ScaleR.  Check the output for more information.
Calls: source -> withVisible -> eval -> eval -> .Call
Execution halted
At C:\Users\USER\Downloads\Churn\SQLR\SQLR-Customer-Churn.ps1:53 char:5
+     Invoke-Sqlcmd -ServerInstance $ServerName  -Database $DBName -Use ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
    + FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

**Comment by jeroenterheerdt** [comment]
@imtiazu if this is still a problem, let me know.
