### ISSUE TITLE
"Forecasting" Table Creation Script is missing

### ISSUE THREAD

**Issue by SajeerAssiz** [Microsoft/SQL-Server-R-Services-Samples#37]
"Forecasting" Table Creation Script is missing

**Comment by jeroenterheerdt** [comment]
in what sample?

**Comment by SajeerAssiz** [comment]
Retail forecasting

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jeroenterheerdt** [comment]
It is here: [create_table.sql](https://github.com/Microsoft/SQL-Server-R-Services-Samples/blob/master/RetailForecasting/SQLR/create_table.sql)
