### ISSUE TITLE
Prediction results are *very* different from the one in AzureML

### ISSUE THREAD

**Issue by yorek** [Microsoft/SQL-Server-R-Services-Samples#6]
Doing the same test (for Boosted Decision Tree Regression) in AzureML and on SQLR, resulting predictions are very different. Here are the result in SQLR

```
Mean Absolute Error: 21.1772554      
Root Mean Squared Error: 27.6586547      
Relative Absolute Error: 0.5759823 
Relative Squared Error: 0.4429988 
Coefficient of Determination 0.5570012
```

and these are the one produced by AzureML

```
Mean Absolute Error: 0.123788                  
Root Mean Squared Error: 0.248766      
Relative Absolute Error: 0.003367 
Relative Squared Error: 0.000036
Coefficient of Determination 0.999964 
```

To be honest the AzureML results seems to be even too great :)

Do you have the same results that I have?

**Comment by hlums** [comment]
Can you specify which sample you are referring to?

**Comment by yorek** [comment]
A sure, sorry. I'm using the "PredictiveMaintenance" sample

**Comment by yorek** [comment]
Any news on this?

**Comment by zhixingr** [comment]
I got the similar result as you with SQLR approach. For AzureML, the following is the result I got:

Mean Absolute Error: 21.283579  
Root Mean Squared Error: 29.615866  
Relative Absolute Error: 0.578874
Relative Squared Error: 0.507913 
Coefficient of Determination 0.492087

Could you double check your AzureML experiment?

Thanks,
Zhxing

**Comment by yorek** [comment]
Sure I'll do right now, thanks

**Comment by yorek** [comment]
I can't repro the problem :( Now I have the same results as yours. I'll try to figure out what happened - unfortunately  the experiment was for a customer that deleted it.... - and let you. Closing the Issue right now
